Feature/48 link backend and frontend so that a user can join groups
GazeDev/groups_app pull request #19
Opened 2020-04-15 21:17 UTC by andreaestrada

Linked frontend and backend to allow users to join pre-existing groups:

- Filter out groups user has already joined
- Add users to selected pre-existing groups
- Auto update groups displayed once joined

Additionally removed dead code (from HousingDB Core).

2020-04-16 04:41 UTC, andreaestrada commented
@zaclittleberry we occasionally get the following error: ERROR TypeError: Cannot read property 'id' of undefined at SafeSubscriber._next (join.page.ts:63). We weren't sure why it was happening sometimes but not always and couldn't figure out how to resolve. Other than that it seems to run smoothly. Any suggestions?

2020-04-20 22:59 UTC, zaclittleberry commented
@andreaestrada Your code didn't change since you copied the error message did it? I'm trying to make sure I'm looking at the right line. The only thing I can guess is that your request to getAccount hadn't finished yet. There's nothing technically stopping a race condition between the getAccount call finishing and the getJoinGroups being called (which uses userAccount.id). You're also making two calls to getJoinGroups. Any requests made to the api should be in ngOnInit instead of the constructor, and you can call getJoinGroups in the subscribe section of getAccount, that way you know it will complete.

2020-04-20 23:00 UTC, zaclittleberry requested changes

2020-04-20 23:00 UTC, zaclittleberry commented on src/app/_pages/join/join.page.ts
> +    this.getJoinGroups();
getAccount race condition with getJoinGroups. getJoinGroups called twice. Any api calls should happen in ngOnInit. Discussed more in the conversation section.

2020-04-29 14:36 UTC, zaclittleberry approved these changes

2020-04-29 14:36 UTC, merged